name: neokeys
description: Get characters from a terminal keyboard, similar to getch in curses.
version: 0.1.1
homepage: https://github.com/neo-dart/neokeys

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  coverage: ^1.5.0
  neoargs: ^0.0.1
  neodart: ^0.1.1
  test: ^1.21.4
